### ISSUE TITLE
Example Error

### ISSUE THREAD

**Issue by IamManifold** [indiespirit/react-native-chart-kit-example#14]
Error One, I updated the sdk to 32.0.0 then i get the next error
```

C:\GitHub\react-native-chart-kit-example-master>expo start
Starting project at C:\GitHub\react-native-chart-kit-example-master
Expo DevTools is running at http://localhost:19002
Opening DevTools in the browser... (press shift-d to disable)
Your project is in SDK version >= 33.0.0, but the expo package version seems to be older.
Error: Using unversioned Expo SDK. Do not publish until you set sdkVersion in app.json
C:\GitHub\react-native-chart-kit-example-master\node_modules\metro-config\src\defaults\blacklist.js:38
  return new RegExp(
         ^

SyntaxError: Invalid regular expression: /(.*\\__fixtures__\\.*|node_modules[\\\]react[\\\]dist[\\\].*|website\\node_modules\\.*|heapCapture\\bundle\.js|.*\\__tests__\\.*)$/: Unterminated character class
    at new RegExp (<anonymous>)
    at blacklist (C:\GitHub\react-native-chart-kit-example-master\node_modules\metro-config\src\defaults\blacklist.js:38:10)
    at getBlacklistRE (C:\GitHub\react-native-chart-kit-example-master\node_modules\react-native\local-cli\util\Config.js:56:8)
    at Object.<anonymous> (C:\GitHub\react-native-chart-kit-example-master\node_modules\react-native\local-cli\util\Config.js:71:13)
    at Module._compile (internal/modules/cjs/loader.js:1075:30)
    at Module._compile (C:\GitHub\react-native-chart-kit-example-master\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1096:10)
    at Object.newLoader [as .js] (C:\GitHub\react-native-chart-kit-example-master\node_modules\pirates\lib\index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:940:32)
    at Function.Module._load (internal/modules/cjs/loader.js:781:14)

Metro Bundler process exited with code 1
Error: Metro Bundler process exited with code 1
    at ChildProcess.<anonymous> (C:\@expo\xdl@57.9.33\src\Project.ts:1861:16)
    at Object.onceWrapper (events.js:421:26)
    at ChildProcess.emit (events.js:314:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
```

Error Two:
```


C:\GitHub\react-native-chart-kit-example-master>expo start
Starting project at C:\GitHub\react-native-chart-kit-example-master
Expo DevTools is running at http://localhost:19002
Opening DevTools in the browser... (press shift-d to disable)
Your project is in SDK version >= 33.0.0, but the expo package version seems to be older.
Error: Using unversioned Expo SDK. Do not publish until you set sdkVersion in app.json
C:\GitHub\react-native-chart-kit-example-master\node_modules\metro-config\src\defaults\blacklist.js:38
  return new RegExp(
         ^

SyntaxError: Invalid regular expression: /(.*\\__fixtures__\\.*|node_modules[\\\]react[\\\]dist[\\\].*|website\\node_modules\\.*|heapCapture\\bundle\.js|.*\\__tests__\\.*)$/: Unterminated character class
    at new RegExp (<anonymous>)
    at blacklist (C:\GitHub\react-native-chart-kit-example-master\node_modules\metro-config\src\defaults\blacklist.js:38:10)
    at getBlacklistRE (C:\GitHub\react-native-chart-kit-example-master\node_modules\react-native\local-cli\util\Config.js:56:8)
    at Object.<anonymous> (C:\GitHub\react-native-chart-kit-example-master\node_modules\react-native\local-cli\util\Config.js:71:13)
    at Module._compile (internal/modules/cjs/loader.js:1075:30)
    at Module._compile (C:\GitHub\react-native-chart-kit-example-master\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1096:10)
    at Object.newLoader [as .js] (C:\GitHub\react-native-chart-kit-example-master\node_modules\pirates\lib\index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:940:32)
    at Function.Module._load (internal/modules/cjs/loader.js:781:14)

Metro Bundler process exited with code 1
Error: Metro Bundler process exited with code 1
    at ChildProcess.<anonymous> (C:\@expo\xdl@57.9.33\src\Project.ts:1861:16)
    at Object.onceWrapper (events.js:421:26)
    at ChildProcess.emit (events.js:314:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
`C:\GitHub\react-native-chart-kit-example-master>expo start
Starting project at C:\GitHub\react-native-chart-kit-example-master
Expo DevTools is running at http://localhost:19002
Opening DevTools in the browser... (press shift-d to disable)
C:\GitHub\react-native-chart-kit-example-master\node_modules\metro-config\src\defaults\blacklist.js:38
  return new RegExp(
         ^

SyntaxError: Invalid regular expression: /(.*\\__fixtures__\\.*|node_modules[\\\]react[\\\]dist[\\\].*|website\\node_modules\\.*|heapCapture\\bundle\.js|.*\\__tests__\\.*)$/: Unterminated character class
    at new RegExp (<anonymous>)
    at blacklist (C:\GitHub\react-native-chart-kit-example-master\node_modules\metro-config\src\defaults\blacklist.js:38:10)
    at getBlacklistRE (C:\GitHub\react-native-chart-kit-example-master\node_modules\react-native\local-cli\util\Config.js:56:8)
    at Object.<anonymous> (C:\GitHub\react-native-chart-kit-example-master\node_modules\react-native\local-cli\util\Config.js:71:13)
    at Module._compile (internal/modules/cjs/loader.js:1075:30)
    at Module._compile (C:\GitHub\react-native-chart-kit-example-master\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1096:10)
    at Object.newLoader [as .js] (C:\GitHub\react-native-chart-kit-example-master\node_modules\pirates\lib\index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:940:32)
    at Function.Module._load (internal/modules/cjs/loader.js:781:14)

Metro Bundler process exited with code 1
Error: Metro Bundler process exited with code 1
    at ChildProcess.<anonymous> (C:\@expo\xdl@57.9.33\src\Project.ts:1861:16)
    at Object.onceWrapper (events.js:421:26)
    at ChildProcess.emit (events.js:314:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
`
```

**Comment by iexitdev** [comment]
Fixed in #17

**Comment by iexitdev** [comment]
This was addressed by PR #17, which modernized the Expo project configuration and dependency stack. The old SDK/Metro errors were from the previous stale example app and should no longer apply on master.
